---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v1
  namespace: organizers
  labels:
    app.kubernetes.io/name: &name prowlarr
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: ceph-block
