---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
  namespace: organizers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: "{{ .PROWLARR__API_KEY }}"
  dataFrom:
    - extract:
        key: prowlarr
