apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:A4hHYpGpWeM=,iv:RIk5KkBHSVLPGqzItP1sDaPyKgM0zKHrUvbAw7F0WFg=,tag:zP7T/4LQNJNRmC4TRJZnBg==,type:str]
    password: ENC[AES256_GCM,data:aDs3Kk7oX2M=,iv:7Xq6jU6YtZqfoQ5Yeq9r3nQb54rJiNoEj6oL0uG9/HY=,tag:8TBMxi1K517HhZXq/060rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2RhNGNXR0ZCcnlqc1lt
            QVNTSkl0cHVXem9DN24venBmQzhhbWNaRUZnCllDc09XekxPZ3J4ajdwN21zNEV1
            dWM1akIvMU0yYnF4S0ZVZHVrMWZaOUEKLS0tIEZmODBJSjc0Z3RYZmFERmNmSzN4
            MjZGZVVaSGlScnV1M3FQRmRvdzN2YjAKTJqhYjV+HodmnoHDrbAQ8+SqIBwch5NJ
            QEXLpSyqQntd5xsMylCMfRhqGD3DD8zoScLSM02fG3MmPAbouxTOhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T01:26:37Z"
    mac: ENC[AES256_GCM,data:eOoMJx3zcFkd6mdrFH4WALV5tDXNe5zy/sKAD9sw3aKJGrF7kHPfndRNUZWOY0bItfdjXOKRWeyvxVe5yft6Z9d6qw5SKB9pbg2W2U6X6y9E2An/+u6CG25k0FqzgIMMfU3kwKqKlY5cXggjls8JgiWyEOagEgZ0/paC2KAt354=,iv:RueS1ebh9zAdGDDq6sN0gL2ErJx00DzeDOnoMDnSOYE=,tag:+/OEHhRoqfYXtV0a+A06lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:RgcotFJho4WabjDX5jop/A==,iv:D7vNsOzqKsT7Fk3KyxeOsiIjXdo1Eyh5CoVrV93GDWk=,tag:p2Kw7kWeWPg14SPFYi7Q3w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:SAza5WFsoZXKskWH17iCDBAanXy3MPQVBA/VdXdNE18=,iv:QyO71FX8H42PcS/Eh6IxyM0TX74IvDMm2c2brs/nees=,tag:lXFphBILVx96EA6MHCmUGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2RhNGNXR0ZCcnlqc1lt
            QVNTSkl0cHVXem9DN24venBmQzhhbWNaRUZnCllDc09XekxPZ3J4ajdwN21zNEV1
            dWM1akIvMU0yYnF4S0ZVZHVrMWZaOUEKLS0tIEZmODBJSjc0Z3RYZmFERmNmSzN4
            MjZGZVVaSGlScnV1M3FQRmRvdzN2YjAKTJqhYjV+HodmnoHDrbAQ8+SqIBwch5NJ
            QEXLpSyqQntd5xsMylCMfRhqGD3DD8zoScLSM02fG3MmPAbouxTOhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T01:26:37Z"
    mac: ENC[AES256_GCM,data:eOoMJx3zcFkd6mdrFH4WALV5tDXNe5zy/sKAD9sw3aKJGrF7kHPfndRNUZWOY0bItfdjXOKRWeyvxVe5yft6Z9d6qw5SKB9pbg2W2U6X6y9E2An/+u6CG25k0FqzgIMMfU3kwKqKlY5cXggjls8JgiWyEOagEgZ0/paC2KAt354=,iv:RueS1ebh9zAdGDDq6sN0gL2ErJx00DzeDOnoMDnSOYE=,tag:+/OEHhRoqfYXtV0a+A06lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
