ansible_become_pass: ENC[AES256_GCM,data:t4GSTKIhXt8=,iv:inDXfzuq4d3KFhBD04KufX9is9UlYCtiLbs16XoglbE=,tag:DD7bhc6otM79ubIteqLdzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjFFa0N2MFRkaEZBMHdG
            VUZFVWltZUhuY0xCUW1mdnZRZ3VCQndsbFhJCnJVZlNCTjdqRnhMWUsxZWtDNXBV
            c0wvSFVQZlppM0lLRHdpSis0c1ZZYjQKLS0tIHY3eDZJcnhUWXpOL01XSmQ1amZ4
            cmNRazNhbVI4VEl0eEQrZHJlMVhPOEUK942wux+f5YI092BU0WBlI5YHV5ENC16x
            ubrjHr8w4LyeyVpUQGAg8JUgIG1qgLIzDxwqyubeQ/HCl1iLYPMnOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:02:32Z"
    mac: ENC[AES256_GCM,data:REUv5M73Na0xGgub6eo3iI6Q/kMW4eSJCYP88Q0XXCGsXsZ4z5MnAb02yshlrjZ54FmsNB2m9+veh+k+VYEwTd50o9rNT/c0O7aLM80B525wfbDP9RrSZEWJlKS/r+HVXeEE5L8JofllShraFx7kCnqXxd1XWFwj5X9ttsa1o7A=,iv:nbZZP+JTV5DuhkVPNKjZcYtSclI1tuMbqK/FAzPLE7U=,tag:BX9ChwHGkvjjPLtK4W17iw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
