ansible_become_pass: ENC[AES256_GCM,data:fJtJtqaNfk4=,iv:/y3pa1Z/PVU+nabdTUkOu/9DwntCy0Vb+DsPLby0XHg=,tag:fzfyOHMw2nZtUrxOakdv9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtblZQR0ZOd2RqbG9wZDVx
            QzkrUUEydUsrZUZQelhoMFlhbHhXQlk5UWtrCkdkVFEvaXJRZlUwOGdUbGQ2ZlpF
            OGRJbmJRVFdmODNIdDhhYUd2a3B2ZlEKLS0tIFBWVU9UWERaV2I4a1orSGp6bVFm
            QmpYOGdGdkwwMlRSUHZwV0lVZmY4S3cK3BSAAoOUz9tnVYeGVrksoqD0U8kY39Ex
            HairGMuhFfWnx/TNG4EsrHdXZ1qBlH0BDeohs/MvovHsKiFbmqgL4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:30:28Z"
    mac: ENC[AES256_GCM,data:5uPlIBaCir7vNOJz8SWt7ac4qvLweRoS8UuEtlnMsZMiWw3m/+II9qT5thDeXKq7N8BjhbgjEaTdvivUl4h4ZkQkkYTSR0T+gQkDJnGgjFLb3DmGptrouLOVafcLN9C6UsUrYFAtAXJ+oEqlUWkjnqy4aRwlOg37fbaCp1/VrLQ=,iv:N5+EYGzHb1DmiXrViO/J2uc8pwchHpkuW7zxgrh4mXI=,tag:mKa3hVdA+6TXpBsODN/jPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
