ansible_become_pass: ENC[AES256_GCM,data:A+pf0VLkAfI=,iv:6SUewkNXFV92kicUsrUqb6gDtYDQpE7KXvH99tHnGxs=,tag:x6EM581Ed34ou61fJr1Srg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU1ZKcWRZUW1nNFliSGg4
            S28rcXJLMTdmN2F0Zk9kVkJQbjA5NkwxQ1NzCmlINkxmYXhncmhBWVpuZzl5NFRv
            MFR5bXYzcmJ1b0JMM1UrM0VLaFFKOW8KLS0tIGpoWnN3YTNRZWxIS1UxRExrTm8v
            Mi91Tk41WlY4QXVyTEpGcDh2VFljcTAKcwXQaXaXz28QU3XikUm7UmyYHoHOj+KP
            RupXcqAptiucC4K1H18df/35fDQ+wfnklLtt2Y2fjJYYKZPzzkybTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:30:29Z"
    mac: ENC[AES256_GCM,data:teDIRQ5UCS35xRTe2rMQo7tiSZw+NvZAEOk1l1E1O4b/CCskaMloDvYSy494F/AJj9FChAyTUcnqBH5vAZ5lRZya2DOOUfRxxkbYzPPCZXvBRNbnt1DOk/440bbiVdD7Q6bpZjLezm1w7LVnpjT/C6xi6D+0RXLud/xJic1UykE=,iv:P2AzBCeRWwY/rS96WDPUkAuzKjzf8KJnWSqIFkXz6XE=,tag:yWjJ1t53A0cw6TtWRRGwSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
