apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:ouxu7IyBp8c=,iv:MzAVHxVfxXyQw5fdKlJnK8ywPvPfkjtGKUQmXkxYyfI=,tag:A5Rb4jqZHlxdIWldcuqKwg==,type:str]
    admin-user: ENC[AES256_GCM,data:OjpCDPM=,iv:YsolQdhYe9yV432aftJEDoQ3iOP2+r++Q4Ihk17nExQ=,tag:kRzSJo5fXOj9EtXe22Nz8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFK3o1N1dWQTA3T3BOdW1p
            dEZNMkpoZG03QjRoVGE2RFphM0RObkgrRkI0CjhrZmFSRDZCTVR0bTlUS1UyMzNs
            MWJLbmZLK1ZpcDhQNHNlVEtoSm9TODgKLS0tIDhWQmJkNFl0bitkUXJXd3ZJMk1n
            UTBWQWdrd1lhTU9XbUhCaEdCSzdNZ3MKQVvVG83C+P4MWf4Wa9K/bP2QV1l1adyb
            Me5NxafbOsgemjF84CKIweCjTPzy7OxnHUfTQHsQIx7Kx8PrWw/nSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:03:56Z"
    mac: ENC[AES256_GCM,data:XaEfq17MHN50ZD9lGZC9mLWSbGYlOkMr86DBz4yU/JHV27w+K7lCI6+shNN7d3C+RsXkgRbfj1hmJM+Lzept34bH/ksWaQ+ZnBNYDzxdoqHlKdbMg0SiBUE7wwrSQNddOWrXS8uOu9KwRkI0bjhLZBWn9H2oAdg7P6H2kHPpQNs=,iv:GLwdUskB5/zwgzaoKrum3qSIBDqvbsgImMPls3JtQTw=,tag:gTpie3ACuJWRWp4qkZ/+mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
