apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:VJD1dlfJOuJeQ9uQVyo55ezRQFxsgeA4,iv:Yu53ADWcYGoZyp9hOASKtgidjbiHRJ7415Qy3Jjdlgg=,tag:Ms5WCYe2uZwBTpBa7j14Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZjZDSy9UUnV1SkVpT0Vp
            YVYxcFF6WERxd2tBWnNUdHJZS2V5b1BKTVhVCjdJTzNVZVBhSnEyRzVnMzRaZlho
            SGpaYUxMdjRrS0ZKTFlnTkFTM0dLM2cKLS0tIFphYldrbFNqZzF6RGV4MDhyWHpB
            dThuYnd2SHk4ZFVGeGNJeUdkUUpUdGcKKPNK863/a0VfDagSXf1kqZfK8Vh7CWKv
            UJ3cDmZmVJDRRQRw0694wAj4HlDyPj3LCzJcZjsnyZeMeJDNY0lE4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:31:56Z"
    mac: ENC[AES256_GCM,data:gr6M4llgSY6PnRclr8ERLFfjQNhNIctqfjSFbAJF9ftGzDmqpz+tZQePJN9pfx6ZjStjHhEVlRJprqHpD+OVmgkQSjJ/Q9OUrQbOreaYbzgpgNbfhUmAFt5nEzoabTFEl2V4l+laBMtcbGaygc7+3suDNlIxSvwk/UvipEVf7AM=,iv:ENh88I7Bkj6ijYI6HLB8CmtrpxDEqyadxRPxuQyCDMA=,tag:VtLCwvMTwMGwaSwLL5vDiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
