---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
  labels:
    routed-gateway: "true"
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    volsync.backube/privileged-movers: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: organizers
  labels:
    routed-gateway: "true"
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    volsync.backube/privileged-movers: "true"
