---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
# - ./secret.sops.yaml
commonLabels:
  app.kubernetes.io/name: authelia
  app.kubernetes.io/instance: authelia
patchesStrategicMerge:
  - patches/env.yaml
# - patches/postgres.yaml
configMapGenerator:
  - name: authelia
    files:
      - config/configuration.yml
generatorOptions:
  disableNameSuffixHash: true
