---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        "redis-password": "{{ .redis_password }}"
  dataFrom:
    - extract:
        key: lidarr
