---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/onepassword-connect-api
              tag: 1.7.2
              pullPolicy: IfNotPresent
            env:
              OP_BUS_PORT: "11220"
              OP_BUS_PEERS: "localhost:11221"
              OP_HTTP_PORT: &port 8080
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: 1password-credentials.json
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 100Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 15
              startup:
                enabled: false

          sync:
            image:
              repository: ghcr.io/onedr0p/onepassword-sync
              tag: 1.7.2
            env:
              - name: OP_SESSION
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: 1password-credentials.json
              - name: OP_HTTP_PORT
                value: &syncport 8081
              - name: OP_BUS_PORT
                value: "11221"
              - name: OP_BUS_PEERS
                value: "localhost:11220"
            probes:
              readinessProbe:
                httpGet:
                  path: /health
                  port: *syncport
                initialDelaySeconds: 15
              livenessProbe:
                httpGet:
                  path: /heartbeat
                  port: *syncport
                failureThreshold: 3
                periodSeconds: 30
                initialDelaySeconds: 15
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 50Mi

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      shared:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /home/opuser/.op/data
            sync:
              - path: /home/opuser/.op/data
