---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mullvad
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mullvad-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mullvad
