apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:eKQFYlmGziR1CRLaShiPxH4CyvVPLHre4/muhS4Z6Nlgxl410RiINlw2AeMh8VTUZLbDQFzT2Cu2JexX,iv:DiBpoM6RyI5WY/vcQWbIoD4VzD6cjiLhpEfhNwaiXts=,tag:WVuBWumeHsJJO7G1xJhInQ==,type:str]
    username: ENC[AES256_GCM,data:oyJg92I=,iv:7lRd5Jl4P6JvKeMKqrN9GpGJJcN0muM6jrkwAsm7gSA=,tag:Nlgd/Rw+xNhE5nEeC1sBmg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TXJYc0pQQWF0K0tad1I3
            UGhNSngwN25xekRYbW0vQ2YrU0kzZ0lYVTFBCmVEKzMySFEwNW80YWNFWVB0QUc5
            bUVsVXRiVUZEb0JKNGlic3l2MCtCTVkKLS0tIGZmWHBjcmZQUHZLVEJKOG1Ndmdl
            MzVJYW9jWnZsUCtVSjNQZVdlSmoxeEUK4709ogBIc9U7Puy8aOfu/d2lOJYg8W3i
            SasZ5+2EMX7aNkmCvZVgxZ8K2b3pnx3gV6MBMm3or3YT+/GZW3XGuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:32:24Z"
    mac: ENC[AES256_GCM,data:5g3B2KjWuroOMRpQkZTn1DxsRN04DxiEbAbDDBIYBvK83moNusS0uBE3koVN4MZyWNtP0XykPGG/NFl6+vDi9pPII92L8cOxqWqWvmb8lW9xFRTObHC3vHbQhZcUIDfE1pMACtDuwHO0P676FbSjTBeh8SUgNM3eQvxE9S6vLDk=,iv:iOhG9EJ8UKschV/jH3FFYP7keu5HwH7yCMM0CCO5WlQ=,tag:bcP4FN1O4AbdzZDK/E2DQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
