---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: organizers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .RADARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
