apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cliUkUzm+mnSKro=,iv:Syuh7IFiVEKO8ZwjvxGLwkoaZx0w0KdITrEYwmGP3y0=,tag:3P1pEKUgZR/yABTgJK3hyg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YHwDV0Acw+TqA8aShk+3cg==,iv:uIpFe+b/xXoFQr7SEb+n+j8pSPHEl2QY9STWoS1+CAw=,tag:7FZsFUEeNOsSHTXQOu9ezQ==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:WrdcYzMpE7h/vJ/C,iv:TVWhgOVNlX/GNM6dsRc82R/MtI2z/vHU8sU+V49PvkE=,tag:hzi/wmFLAz4IhLZekyYQiA==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:pJPopfOaBwbRwQ==,iv:TJA3tQSaRUakV6kU/8Jb1kd7GNLGClYsi1Z4MPebY4g=,tag:T1jZSNT7r/Ph6u8b/9hxRw==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:WJc2mIoIqOzbbA==,iv:7+lR+QB02vHD6oVLM8CHiVscgfU3IFqVAPdtl3gv9Dc=,tag:WuQIa4gu4P4hTbjH/9xa8Q==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:fGoKNXTcn7BarA==,iv:A90NvfnSnfLwYnDgqAQ00JM7pv8g2bZri9HyNrcH8ho=,tag:3taIUFU3x74lQZ+6TbMuww==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:PhCUF2MNRYqKnQRiAV3LbREHK9fFDMbwWf2U,iv:87ghkyVjH3ZHqJICF1eEZRjb9WDHwOj+w4xUfP2QGrM=,tag:yfiYbk7eJXMglXZd2QNC2A==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:+j87heDbAKHCSoW+cnNwbQ==,iv:KMQCiWFi0Ynq1wSLAHv+SFW3cPOtsclwaH3AvnOoIPI=,tag:x4a0hJ3gtgA9e2ZRorDcQg==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:oHxqxrwLEzbewrM=,iv:yD8eVp8B8k06fpE8x5Wp+c45slDFWq8vh930R7EsBJw=,tag:xi5RfNqWT9euWlT4u5yoWQ==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:Bt0S7advO3sTbB/wPkG1NvY=,iv:47Czb9vqzHxcwmrLUfHT3zCMPSKiNXkz8Hwx65E9n5o=,tag:s+T6wTjNDrqQhap1g1HhRw==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:Fb/2WKgSgAp8tUVvvGE=,iv:N5uCIJfT9yojguajoMrZGYk/hiKkaiDaa2Bnb6FhaRg=,tag:7g8rUhAPutN4lrYpDDeW8g==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:RsMKuIDEbmSs/joJPN0=,iv:ltz6305AtNThuPpp9FFz85pS+jA/1/yBFJTwoqBmlMA=,tag:4RM6LQbw/Hf61ns+jUEicg==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:LT/6rPp0sN6lA+YYo8I=,iv:iCOLP7eNN5RBgdaqhnCxQ/cJ6rqIwApRE7Yj6KqwmNc=,tag:juW3dHPdY5XLmWc1ClTslA==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:SzGfPwHZJtFmmHECbru/I/VjaQ==,iv:NjyVmMMhtXm6hro9YsZHjUYIJ9xml5LH1Qp9axKsNzs=,tag:3+XQsGxI5g8wcvp1Z/0+8w==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:Ra16aw1of5httGmxTfK5iv/LTg==,iv:pybgLDq4uyAA+QskeWdqa2YGjvxH35/VY42GDMODd90=,tag:oLgWbTtprt43Yr8/V9CStA==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:kLVOZz5gBb0vIg7lv4MW08EnpRdsThw=,iv:7YfPeVrGu/0CqXlrakRWAHgjr4O/spfrPWSJ/sWA5yI=,tag:L/G12tD3PhN62rypvBeP3w==,type:str]
    EMAIL: ENC[AES256_GCM,data:20XIFCyQZYijewKEara6uQ==,iv:p9dpqiUmXFn3aLrdOLiJEC8C4tDLzZV9iiQ6O2bknaA=,tag:M1tZmy7YaKTACT/1z07A0Q==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:Z/yJ6j0efu2sosbvcNyQfop0qCKijftGS+Bm7bLm+CD3vkw=,iv:6dzXTOd785ti67iEx6sQwDdfovDUsa+e9niQrv7pL28=,tag:1znxTLvv6oMrjXyJTU+5GA==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:Q+Ym2rqfuUfW47Ha,iv:eR/tzblRQErwB4GPW09XVnRqykbgjoICacDpUzPHOuw=,tag:k+BkhMkBMo6W2NHGA48agQ==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:w5u9dz8OURUCfqvt,iv:5fScZavC747FhsbKpmSlEsP2fgQsCk+z3d0emRuuzyw=,tag:ZJFDGiaorSSseK943Ch6CQ==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:Lp6eOo0=,iv:rWWf89JmfzzNyTHB7eSCZiQxhPcSPcPxJfRrqyfZG2k=,tag:4X0XiKg/jA0J0SL9t/K8wQ==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:wdB5Dh2Vk6ackA==,iv:sXdYjp0oivBwqaap7+g6+J5kogAOPGFZwTiZUMVZbQc=,tag:X7N9vxx8dcpPyBEt+2HV2g==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:RkpEZTNS/9Ej9KhljUc=,iv:rM0XFHzG2DhkXDidF/CggqedZ2XRjpLec4B1uOPEGV4=,tag:bCD5lt+OjnowJYVBwlz90w==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:OlAO8jUSg+s=,iv:Oab43rMQ5yN0nuGJlQbiDEhiuWW6604Zosbp4oT+77A=,tag:yqle85r9KvYSMlqo93iGiw==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:yb8uwOk=,iv:Vt5hE/X1xCWISOXkVEhYNrgc0Nt9szs5Q8ZAanjwf2M=,tag:N0SiFPWy/NSpmRjQhJG01w==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:Qd/zqdGaL8Q=,iv:u9Xpm1Ic4r16aQ1spJEEmI7LZfwSkhxtA1HoE7QcalM=,tag:BXvHwEGKvW3nxOnrmo0uew==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:aJIjFMujsYee+ZfBdzQ=,iv:d6JmxRnqiqRaG5ejnRvmFes7Ioag4GDKcNelRKhxTE8=,tag:RomeMhcfZjTA5qng7DOcyw==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:pZOUT/YFw/c=,iv:uwmPSZjbavSOuLNG+MwgCA9D4SE7ZKfKhIT7GfBXC+8=,tag:BrKnRqofwX84gIA2JZTjHQ==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:OJsa45umMTE=,iv:IleIwjVXDZSBQCFQDLlLbHdWtvbppiLWzOoRkqCNYOg=,tag:C1z9eLlZdo2hblM+VDt/nA==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:4M7vjywvY58=,iv:z0lfK7Tg1cU3PZcZd8dUPT3izHKFEZUxZNAXNNSbDDk=,tag:GM9yEqkNZHQho7y334+aeg==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cNyNsx+2Mi8TJspch0FHvrvkSw/WLypolyY=,iv:RaHaHWVqYAkM/ZN62oOa3oUivF3xd+rNtJeQeP7Cn9w=,tag:HViYAQYKe7cT9/azbHumjg==,type:str]
    TZ: ENC[AES256_GCM,data:tkel3UNVu6u658ntUBVIQNmgq9M=,iv:84DeyWheXLk2/fv/Ug/JnGO0d790+zcxKxGt8js80Wk=,tag:f2nvhpX5KG08RkWjRY0HSA==,type:str]
    #ENC[AES256_GCM,data:pgmL2D7EH/4OkES8mUJd17LhFEtOz1oqnQKPZcuefH+1S0hE9bI9hJcYtovVr2XhdbEQPtaEjDw2LgzfxnUniVxNq3e9mLDDZ/oM1XJUTiA=,iv:P+PmT/Ysfp8yq/Z3lZj/vkvX/VBDKfZu63WNJ7NwWQo=,tag:KyV331fpFc7W6uWzV0YQfw==,type:comment]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:hupBmBiP8PCmIQ==,iv:rZNC8QEAzNiKBFDHg1vg89qr7Qc2sX1NqxQy1Jqq1uo=,tag:lt2LtUihqY4aNczE1Tzddg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:8q2oTQiN1A==,iv:2D0m9Yt+j0Nz6eiu4LXIp9u3O00Zd0aT9LQ+4EgSw6g=,tag:IEftf3Q4M10V7kiAJHYqgg==,type:str]
    VNC_USER: ENC[AES256_GCM,data:6bFuu5Q=,iv:Ij28537DpHF6AdmCYAQvDBIiMfwTtUzOggRcbDL+0DQ=,tag:SZCskX4JyEpuHsNT9tVe/A==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:IhMp8Ip/3B8=,iv:EcSRG6NcUrY6KlaQL9w81wMxC9WPeQVTAYGZFFuVz1M=,tag:D4GgSTCPQDcvKwWQtZBCdA==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:plsQZgC8cdw=,iv:K7Xj00+jAfUBAq5/i3Pva3t3uXy0JvvIXslvoeUpDHs=,tag:vjtR+U3uCIrwyEHWViYFZw==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:BFhhIHRqw0I=,iv:ED70P3CDDHadXeUXuCXoY6zsTRlypiS9tjqqtpMQqpE=,tag:ZaePFmbHg2TWCXNbO0uLCg==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:c84OxG0=,iv:LPpTiu/yayof2ca/pqNNIkhoZlkJ1cu8mMehpNcFjY0=,tag:9VEE22KuIRmJMdKgAkPI6Q==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:r+qNriRQYFI=,iv:NdRCnNKf76VwcmfQd+gJaTafnOIpA2E35BMvr3z38gw=,tag:t2c/jtgBmD1/717ivHJ/3A==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:SdLb/TrIQprjzA==,iv:y+dMkGMUSqK+fjKQyEnfw5I5JUX2tGIhq+e6dSaJ4bk=,tag:NVvJ7cpdwZVvKjScbL0aRA==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:Ru88hHT93zNhcAq8j3gWkw==,iv:TTeks283ALLKYarQ7gbJRRGQQu9i78mRNEwmA7M2aJg=,tag:zhoUn7xIkqLMRT6x8iHX1w==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:3lBRG/zDf2E=,iv:ARkPMTkcCxOc+E8/qN62Sp9DN9W/aLhlj5LE9b6asgQ=,tag:cw3Vyw3Bl0DS0lY3w2b26Q==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:Q7jqEWEBr/dKz9kpmnePZw==,iv:GMzXXWZFwjEC2jNoAGwoCSKijgPXKE/PY1dtAJVKpdg=,tag:axlVnImrLf0UCr+Al8gqhg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:/dVbWDVjjcFpWVs=,iv:XnsZm47HzHnSBaBgu+8iub/4TU5LuPe0RVYoYkSzy/0=,tag:p2LoM/d7wkUocP6I/MOpXQ==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:IVjamhSzj+uh6N9EKA6HiB2ezPLkfgAwFLA=,iv:ucb6JaD85Ig8aWsBKXAT9CKc/o5i+sxpUU3lOnXscqM=,tag:MclcZy6Lb1Gg52Qo0BsWuA==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:xI03nJ3cnbIlRoI2LaQYPuLO7KiCVvcHDxA=,iv:h/dG2RilMqethqCNqtM8KeZZUPECfm6SFPgwlz02ZjE=,tag:V9UxMpwBTrXjMOrU+4dl8g==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:d6kKslBoQQ==,iv:LqM/V14u2EuXIks6L7WpMNYs2Ge7+P9n6r8g0k/oqsg=,tag:dd9G4rcskkCjIqQ965RfFw==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pFUp9PHXF4o19yelg4S3PO0GqzABnfdPePY=,iv:zVb4dNChV8vTHklm2HNFTRYModFP3ErjQIe7s5+p7jw=,tag:atlI3EH5sQxz/f7OhimVKQ==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:IJ1QmzrL4kfqLSX4bfz6KHX6J/AX5oRbSR+cS8kmcPE=,iv:ko3P1KIYr/mFfgYuF8udnXPsaFVqKKTSjroDc/gv7hM=,tag:F960rWeXCUJ6/o4mH5xhAQ==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:+n5d2CWnHJ0=,iv:VPnwXX+XOLq8vpgpw/Xa8Vo+EulIME7Ssd/AmK6wyyU=,tag:AN6/ZASN8fJ74B7+Mi9Njg==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:kHEh1wUeS8s=,iv:3jUm9+pzX+O30bicxQL4jwhWQvOV3ykwkJvIzmfA0Cc=,tag:y+3WR/B29jh+TH/K8YkHjQ==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:Ja2G3fZWrZzE+LQ=,iv:+HVmAzv/6e9qdD1hKoOs/qCcKY+MqMYMgKiTr1O8JVI=,tag:Sx5bknMkhmPg1fdjUpEYHw==,type:str]
    QNAP: ENC[AES256_GCM,data:ZOh9Km2ZUh+H7u4=,iv:TxfueVY8f5z5gZhZGc1SlgSmy2o7TTpQB+dwrQa3xKk=,tag:fN8BOuNtksCjkIvrW7V90A==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:Q93JMw==,iv:6PHAcOVRk4cT/FzLohU95rg5oxBgupyjnxfJBxHBlZ8=,tag:jl8W1lJeeoVNozg+wc7HMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzazNOOGFBWURkYjZZcGtM
            K3B0dHNCTmliZXZUa09ZOENsWFJYWGRyb2lvCkNTZTJTQndublpCSVNHdGJPa2M2
            b3FzVGxxbkV2VlNvNEhiZ2grelhKSTgKLS0tIDNtcS9vTFYzN2hFZkx6bzZEOWJs
            c0dZNHZwSTZ0c0Z1bHBaL2hWQTkzMlUKtjSDaTJjS00tblasdlcsidGrdqXqG+wl
            Bpa3X25V43LaJMhzwEe7sAxrkhr2HJ8gXChbNnF3mvlg3korCMnU6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T06:21:35Z"
    mac: ENC[AES256_GCM,data:RtUQi3zdM2KnfsPWyrXJlFESVTykKZmgAqJ7j4oug3lKmovYwb0yCKb5rzxWLFEkaOvjV6GrxF/LW5c9cp6Ox8kV3BkNcu5ia9HlweS1kRUVuDu7o9YKXL4z5SN/2mjFIB7ofI9Iw2N009HnHjf3yGAmX/FOKtqKQG6hpRJbR24=,iv:IW/SrPOnYFnWCKVbT74ovBSHsKh1DCcvxHA3zh0s/Bw=,tag:8Bs0in7pkUIT0OyhYMO44Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
