---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux-Kustomizations
  - ./lidarr/ks.yaml
# - ./prowlarr/ks.yaml
# - ./sonarr/ks.yaml
# - ./radarr/ks.yaml
# - ./readarr/ks.yaml
# - ./readarr-audio/ks.yaml
