apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:chHAK9NQGORRajVW1EB9oYluKqyITTPGVmiSAn4xFQDz9eId,iv:KCAxVUXTtmmteA6Lj+iReL6pcRXZlZ47x4EKr3+zKoc=,tag:/qH75kStEaJkx1aU65pEvA==,type:str]
    credentials.json: ENC[AES256_GCM,data:B/dkz+OQtVG4upgNWS1DzgpSGeLpMLedv3uGE4xW1NyqmbixwMlStyQeLMeLcdbHOVA/GNM/+scgLY8sSBoFuk5sU0GtENyg7Ter8NKmFoiy97go1LW3IYi/Kppk37YGUiBbi25mt/5LJOcgVnRqeFPA8Us+QeS1unWZnRxwswS8ilUTCcvqrev3GV5mKEMkbIczHTWlZoRnDPv68ZOD+4Z2XWOHnD6hWrbdbBSHXg==,iv:FAW1JOEp7jvW3OjuOOMGtnFBK/SR85ZbCDDwuiF47aI=,tag:Y9eqdW4QpqJ3rytu7DdPow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M2xXZ3ZFbWlpczJDY0hV
            UmE2Y1Z3K1p2aW9QMzVyYUlJN0Z2akVoS0djCnhaemc4djh2WFp6Y0ZuczlmQ3Ev
            RmdtdHQvTEYrRnZ6SHBlN3BaL3V3MlUKLS0tIFZwdUxHQjBpbkRUdCtkN1JiTG1D
            S2JhQStRNFVmYWZ2b3NxcXFPaml0SVkKv9HcAfpL62kRW60yoMnPUZu3TqMdVf0l
            uPSVwxSrQyOHK3ZLwPjqqMVkHrv+umolH4VmZqjL87a0K2PWjuvRmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T01:03:48Z"
    mac: ENC[AES256_GCM,data:DiHKjSQMOJhriBjxi3DFb6akjY840YkSZjRR5+TFkaBnLSKSSxVjRheTg5JdVSmZQNIh1139H+ex0O2po1Es6VBlZo65YISCb3Oqd7KTey/82vCr+hgvEpn/ebuQTZ7/wFsbceHMGdjuqHNn+vL5rnMMvpzX7e5vjD02H81zs90=,iv:ZbELOCzjkOD/k9aaIc1zHCnzzFtJpWovrrwTYyUDGmI=,tag:W0p/tXLRTqQjBHPeMaQs4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
