---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
# - ./gatus.yaml
# - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: readarr-audio
  app.kubernetes.io/instance: readarr-audio
