---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sonarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-onepassword-connect
    - name: cluster-apps-pod-gateway
    - name: cluster-rook-ceph-cluster
  path: ./kubernetes/apps/organizers/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sonarr
      namespace: organizers
  interval: 30m
  retryInterval: 1m
  timeout: 3m
