---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph
    # version: v1.10.11
      version: v1.13.1
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    monitoring:
      enabled: true
  # image:
    # repository: rook/ceph
    # tag: v1.11.0-14.gd70d8ad60
    # pullPolicy: IfNotPresent
