---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRESS_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        MINIO_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg-superuser
    - extract:
        key: minio
